"""add_background_task_processing

Revision ID: 634a6e31b0ae
Revises: 0bda935980b3
Create Date: 2026-01-13 14:53:14.005754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634a6e31b0ae'
down_revision: Union[str, None] = '0bda935980b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['processing_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.add_column('import_notion_task', sa.Column('job_id', sa.String(length=255), nullable=True))
    op.add_column('import_notion_task', sa.Column('queue_name', sa.String(length=50), nullable=True))
    op.add_column('import_notion_task', sa.Column('worker_id', sa.String(length=100), nullable=True))
    op.add_column('import_notion_task', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('import_notion_task', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('import_notion_task', sa.Column('result_data', sa.JSON(), nullable=True))
    op.add_column('processing_task', sa.Column('job_id', sa.String(length=255), nullable=True))
    op.add_column('processing_task', sa.Column('queue_name', sa.String(length=50), nullable=True))
    op.add_column('processing_task', sa.Column('worker_id', sa.String(length=100), nullable=True))
    op.add_column('processing_task', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('processing_task', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('processing_task', sa.Column('result_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_task', 'result_data')
    op.drop_column('processing_task', 'max_retries')
    op.drop_column('processing_task', 'retry_count')
    op.drop_column('processing_task', 'worker_id')
    op.drop_column('processing_task', 'queue_name')
    op.drop_column('processing_task', 'job_id')
    op.drop_column('import_notion_task', 'result_data')
    op.drop_column('import_notion_task', 'max_retries')
    op.drop_column('import_notion_task', 'retry_count')
    op.drop_column('import_notion_task', 'worker_id')
    op.drop_column('import_notion_task', 'queue_name')
    op.drop_column('import_notion_task', 'job_id')
    op.drop_table('task_item')
    # ### end Alembic commands ###
