"""
Application configuration management
Supports development, testing, and production environments
"""
import os
from datetime import timedelta


class Config:
    """Base configuration"""
    # Flask Core
    SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')

    # SQLAlchemy
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ECHO = False  # Set to True for SQL query logging

    # Database
    DATABASE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data')

    # Encryption
    ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')  # Generated by Fernet

    # File Storage
    UPLOAD_FOLDER = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'uploads')
    CACHE_FOLDER = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'cache')
    BACKUP_FOLDER = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'backups')
    MAX_CONTENT_LENGTH = 100 * 1024 * 1024  # 100MB

    # API Configuration
    API_TITLE = 'Notion KB Manager API'
    API_VERSION = '1.0.0'

    # Logging
    LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
    LOG_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'logs')
    LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

    # CORS
    CORS_ORIGINS = ['http://localhost:3000', 'http://localhost:5000']


class DevelopmentConfig(Config):
    """Development environment configuration"""
    DEBUG = True
    TESTING = False
    SQLALCHEMY_DATABASE_URI = f"sqlite:///{os.path.join(Config.DATABASE_DIR, 'notion_kb_dev.db')}"
    SQLALCHEMY_ECHO = True  # Log SQL queries in development


class TestingConfig(Config):
    """Testing environment configuration"""
    DEBUG = False
    TESTING = True
    SQLALCHEMY_DATABASE_URI = f"sqlite:///{os.path.join(Config.DATABASE_DIR, 'notion_kb_test.db')}"
    # Use in-memory database for faster tests
    # SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'


class ProductionConfig(Config):
    """Production environment configuration"""
    DEBUG = False
    TESTING = False
    # Use PostgreSQL in production
    SQLALCHEMY_DATABASE_URI = os.getenv(
        'DATABASE_URL',
        f"sqlite:///{os.path.join(Config.DATABASE_DIR, 'notion_kb_prod.db')}"
    )
    SQLALCHEMY_ECHO = False


# Configuration dictionary
config = {
    'development': DevelopmentConfig,
    'testing': TestingConfig,
    'production': ProductionConfig,
    'default': DevelopmentConfig
}
